### ISSUE TITLE
add include context and clusters for easy copy paste yaml file in `kubeconfig`

### ISSUE THREAD

**Issue by jetersen** [fydrah/loginapp#23]
**Is your feature request related to a problem? Please describe.**
Would be great to update the `kubeconfig` to include clusters and contexts.
At the moment we end up passing around our kubeconfig instead using the loginapp for both clusters and contexts.

contexts is again often used to shorten cluster names, so would be great to also include these in the shared

```
clusters:
- cluster:
    server: https://k8s-dev.host.tld:6443
  name: some-long-name
- cluster:
    server: https://prod:6443
  name: prod
- cluster:
    server: https://stage:6443
  name: stage
contexts:
- context:
    cluster: some-long-name
    user: user
  name: dev
- context:
    cluster: prod
    user: user
  name: prod
- context:
    cluster: stage
    user: user
  name: stage
users:
- name: user
  user:
    auth-provider:
      [...]
```

**Describe the solution you'd like**
Improve the `kubeconfig` to make it the default place to grab your kubeconfig.

**Describe alternatives you've considered**
Currently passing the files around in privat messages or in many other forms.

**Comment by fydrah** [comment]
hi @jetersen ,

yes loginapp currently only output credentials for kubeconfig, but there is a `clusters` section available (where you can provide a list of all your clusters). Does this not solve the problem ?

If you provide the following configuration to loginapp:

```yaml
clusters:
- server: https://k8s-dev.host.tld:6443
  certificate-authority: |
    -----BEGIN CERTIFICATE-----
    XXXX
    -----END CERTIFICATE-----
  name: some-long-name
  insecure-skip-tls-verify: false
- server: https://prod:6443
  certificate-authority: |
      -----BEGIN CERTIFICATE-----
      XXXX
      -----END CERTIFICATE-----
  name: prod
  insecure-skip-tls-verify: false
- server: https://stage:6443
  certificate-authority: |
      -----BEGIN CERTIFICATE-----
      XXXX
      -----END CERTIFICATE-----
  name: stage
  insecure-skip-tls-verify: false
```

This will output something like (this)[https://github.com/fydrah/loginapp/blob/master/docs/img/demo.gif]

**Comment by jetersen** [comment]
we already have the cluster config but currently only seeing the cluster config as cli commands. Perhaps we have a outdated loginapp version.

**Comment by jetersen** [comment]
The idea was to have the kubeconfig configured as a whole instead of running kubectl config commands to add all the clusters.

This tool: https://github.com/corneliusweig/konfig
Might be helpful to import the whole kube config in one command.

**Comment by FrederikNS** [comment]
I'm actually also rather interested in getting the complete kubeconfig. That means including all the `clusters` and `contexts`, as well as `apiVersion`, the generated `users` and even a `currentContext`.

That would make it very simple for new people to simply go to the loginapp download a complete config at dump it into their `.kube` directory. There could even be a `Download kubeconfig` button.

It would also enable easy importing using the `konfig` tool @jetersen mentions above.

**Comment by fydrah** [comment]
okay, in addition of credential kubeconfig format, a full kubeconfig like this one:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: CA_B64
    server: https://kube.example.com:6443
  name: cluster1
contexts:
- context:
    cluster: cluster1
    namespace: default
    user: admin@example.com
  name: cluster1/admin@example.com
current-context: cluster1/admin@example.com
kind: Config
preferences: {}
users:
- name: admin@example.com
  user:
    auth-provider:
      config:
        client-id: loginapp
        client-secret: REDACTED
        id-token: REDACTED
        idp-issuer-url: https://dex.example.org
        refresh-token: REDACTED
      name: oidc
```

I think this can easily be achieved, if `len(clusters)>0` and  add a config key like `web.defaultCluster: cluster1` (if `len(clusters)>0`)

**Comment by FrederikNS** [comment]
Yes, that's exactly what I was trying to explain!

**Comment by fydrah** [comment]
![Screenshot from 2020-05-11 17-38-20](https://user-images.githubusercontent.com/10036180/81580920-55b8fa00-93ae-11ea-8199-8b57f3570761.png)

Is something like this OK ?

**Comment by fydrah** [comment]
This has been generated with the following config:
```yaml
---
name: "Kubernetes Auth"
listen: "0.0.0.0:8443"
oidc:
  client:
    id: "loginapp-local"
    secret: ZXhhbXBsZS1hcHAtc2VjcmV1
    redirectURL: "https://loginapp.127.0.0.1.nip.io:8443/callback"
  issuer:
    rootCA: "./test/generated/ssl/ca.crt"
    url: "https://dex.172.17.0.2.nip.io:32000"
  extraScopes:
    - groups
tls:
  enabled: true
  cert: ./test/generated/ssl/loginapp.crt
  key: ./test/generated/ssl/key-loginapp.pem
clusters:
  - name: myfakecluster1
    server: https://myfakecluster1.org
    certificate-authority: |
      -----BEGIN CERTIFICATE-----
      MIIC/zCCAeegAwIBAgIULkYvGJPRl50tMoVE4BNM0laRQncwDQYJKoZIhvcNAQEL
      BQAwDzENMAsGA1UEAwwEbXljYTAeFw0xOTAyMTgyMjA5NTJaFw0xOTAyMjgyMjA5
      NTJaMA8xDTALBgNVBAMMBG15Y90wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      -----END CERTIFICATE-----
    insecure-skip-tls-verify: false
  - name: myfakecluster2
    server: https://myfakecluster2.org
    certificate-authority: |
      -----BEGIN CERTIFICATE-----
      MIIC/zCCAeegAwIBAgIULkYvGJPRl50tMoVE4BNM0laRQncwDQYJKoZIhvcNAQEL
      BQAwDzENMAsGA1UEAwwEbXljYTAeFw0xOTAyMTgyMjA5NTJaFw0xOTAyMjgyMjA5
      NTJaMA8xDTALBgNVBAMMBG15Y2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
      -----END CERTIFICATE-----
    insecure-skip-tls-verify: false
```

```
./build/loginapp serve -v -c test/generated/loginapp-config-manual.yaml --oidc-issuer-insecureskipverify
```

New config available:

```
web:
  kubeconfig:
    defaultCluster: mycluster      # or cli arg --web-kubeconfig-defaultcluster mycluster
    defaultNamespace: default  # or cli arg --web-kubeconfig-defaultnamespace default
```
