### ISSUE TITLE
Google OIDC: Error 400: invalid_scope invalid=[groups]

### ISSUE THREAD

**Issue by r0bj** [fydrah/loginapp#30]
**Describe the bug**

I use google as OIDC issuer. loginapp default OIDC scope is: "openid", "profile", "email", "groups". It seems that I can only add more scopes via configuration `oidc.extra.scopes` but I cannot change the default. It can be problematic in case of google because google is not accepting scope "groups", error message is generated:
```
Authorization Error
Error 400: invalid_scope
Some requested scopes were invalid. {valid=[openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email], invalid=[groups]}
```

**Loginapp & Dex version**
loginapp: v3.1.0

**Configuration**

Current loginapp (and eventually dex) configuration (*without secrets*)
```
name: "Kubernetes Auth"
listen: "0.0.0.0:5555"
secret: REDACTED
oidc:
  client:
    id: REDACTED.apps.googleusercontent.com
    secret: REDACTED
    redirectURL: http://example.com/callback
  issuer:
    url: https://accounts.google.com
    insecureSkipVerify: true
```

**Expected behavior**
I can change default OIDC scopes to be able to remove "gropus" to be able to satisfy google OIDC provider.
