### ISSUE TITLE
Add config parameter for context name in generated kubeconfig

### ISSUE THREAD

**Issue by r0bj** [fydrah/loginapp#31]
**Is your feature request related to a problem? Please describe.**
Currently context name in generated kubeconfig consists of `<cluster_name>/<username>`, eg.:
```
apiVersion: v1
kind: Config
contexts:
- name: mycluster1-us-east4-a/username@example.com
  context:
    user: username@example.com
    cluster: mycluster1-us-east4-a
    namespace: default
```

Usually username part is redundant and makes context names quite long. It would be useful to have an option how to build context name. In my case I would use context name as a just cluster name, e.g.:
```
apiVersion: v1
kind: Config
contexts:
- name: mycluster1-us-east4-a
  context:
    user: username@example.com
    cluster: mycluster1-us-east4-a
    namespace: default
```
Parameter could be hidden under config in e.g: `web.kubeconfig.contextName`.

Related code: https://github.com/fydrah/loginapp/blob/master/web/templates/token.html#L109

Is it possible to consider such change?
