### ISSUE TITLE
Better compatibility with Google OpenID Connect: refresh-token

### ISSUE THREAD

**Issue by r0bj** [fydrah/loginapp#32]
**Is your feature request related to a problem? Please describe.**

Currently it is possible to use Google OpenID Connect as a loginapp OIDC issuer to generate kubeconfig but unfortunately generated user config lacks `refresh-token` field so after it expires (couple of minutes) we need to repeat auth procedure again. Using option `offlineAsScope: true` is not working because Google responds with:
```
Error 400: invalid_scope
Some requested scopes were invalid. {valid=[openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email], invalid=[offline_access]}
```
So I guess Google is handling `refresh-token` differently.

Example of kubeconfig users section generated by loginapp:
```
users:
- name: username@example.com
  user:
    auth-provider:
      config:
        idp-issuer-url: https://accounts.google.com
        client-id: REDACTED.apps.googleusercontent.com
        id-token: REDACTED
      name: oidc
```

Example of kubeconfig users section with refresh `refresh-token`:
```
users:
- name: username@example.com
  user:
    auth-provider:
      config:
        client-id: REDACTED.apps.googleusercontent.com
        client-secret: REDACTED
        id-token: REDACTED
        idp-issuer-url: https://accounts.google.com
        refresh-token: REDACTED
      name: oidc
```

Would that be possible to make loginapp more compatible with Google OpenID Connect in terms of `refresh-token`?

**Comment by r0bj** [comment]
After Google docs https://developers.google.com/identity/protocols/oauth2/openid-connect#refresh-tokens
> To request a refresh token, add set the access_type parameter to offline in your authentication request.

and
> access_type: The allowed values are offline and online. The effect is documented in Offline Access; if an access token is being requested, the client does not receive a refresh token unless a value of offline is specified.

**Comment by r0bj** [comment]
It seems that Google implementation OpenID Connect is a little different in terms of offline feature, after https://godoc.org/github.com/coreos/go-oidc
```
    // ScopeOfflineAccess is an optional scope defined by OpenID Connect for requesting
    // OAuth2 refresh tokens.
    //
    // Support for this scope differs between OpenID Connect providers. For instance
    // Google rejects it, favoring appending "access_type=offline" as part of the
    // authorization request instead.
```

**Comment by fydrah** [comment]
Hi,

To achieve this I think you can use extra auth code options :
```
oidc:
  extra:
    authCodeOpts:
      access_type: offline
```

This will add the key/value our as an extra parameter

**Comment by r0bj** [comment]
I'm not sure if I fully understand it, after adding those config parameters, `access_type: offline` was added directly to the resulted kubeconfig:
```
users:
- name: username@example.com
  user:
    auth-provider:
      config:
        access_type: "offline"
        idp-issuer-url: https://accounts.google.com
        client-id: REDACTED.apps.googleusercontent.com
        id-token: REDACTED
      name: oidc
```

So instead of expected additional fields `refresh-token` and `client-secret` there is `access_type: "offline"`.

**Comment by fydrah** [comment]
From what I understood, google is waiting for "access_type=offline" in request instead of a scope. If it is correct, adding this option just append this on the authorisation code url, like this one:

```
{"level":"debug","msg":"auth code url: https://dex.172.26.0.2.nip.io:32000/auth?access_type=offline\u0026client_id=loginapp\u0026redirect_uri=https%3A%2F%2Floginapp.172.26.0.2.nip.io%3A32001%2Fcallback\u0026response_type=code\u0026scope=openid+profile+email+groups\u0026state=QHKcLN....
```

**Comment by fydrah** [comment]
> I'm not sure if I fully understand it, after adding those config parameters, `access_type: offline` was added directly to the resulted kubeconfig:
> 
> ```
> users:
> - name: username@example.com
>   user:
>     auth-provider:
>       config:
>         access_type: "offline"
>         idp-issuer-url: https://accounts.google.com
>         client-id: REDACTED.apps.googleusercontent.com
>         id-token: REDACTED
>       name: oidc
> ```
> 
> So instead of expected additional fields `refresh-token` and `client-secret` there is `access_type: "offline"`.

oh, is seems loginapp templating does not handle refresh token display correctly in this case..

**Comment by r0bj** [comment]
I was able to get from Google OIDC desired fields by adding extra config parameters:
```
oidc:
  extra:
    authCodeOpts:
      access_type: offline
      prompt: consent
```

It allowed me to generate kubeconfig like this:
```
users:
- name: robert.jerzak@fandom.com
  user:
    auth-provider:
      config:
        access_type: "offline"
        prompt: "consent"
        idp-issuer-url: https://accounts.google.com
        client-id: REDACTED.apps.googleusercontent.com
        id-token: REDACTED
        client-secret: REDACTED
        refresh-token: REDACTED
      name: oidc
```

So success, there are additional fields `refresh-token` and `client-secret` which should help with refresh authorization after token expire.

However I'm not sure why there are those fields from config pasted directly in kubeconfig: `access_type: "offline"` and `prompt: "consent"? AFAIK those fields are supposed to be send as a request parameter to the issuer and are not useful in final kubeconfig.
