### ISSUE TITLE
{"level":"fatal","msg":"'Web.Kubeconfig.ExtraOpts' expected a map, got 'string'"}

### ISSUE THREAD

**Issue by sense-amid-madness** [fydrah/loginapp#39]
I'm trying to migrate from the old loginapp "objectiflibre/login-app:latest", and cannot get this one here to work. What I am currently getting is

{"level":"fatal","msg":"1 error(s) decoding:\n\n* 'Web.Kubeconfig.ExtraOpts' expected a map, got 'string'","time":"2021-01-02T23:33:48Z"}

in the logs the loginapp Kubernetes pod, same as in the previous issue. I tried to add the suggested snipped to the config, but still the same error.

Any help appreciated, in particular a suggestion for a minimal working example for a config file which can be mounted to /app/config.yaml, using a deployment applied directly with kubectl.

**Loginapp & Dex version**
loginapp: `latest (v3.2.0)`
dex: latest (not relevant yet I think)

**Configuration**

Current loginapp (and eventually dex) configuration (*without secrets*).
I am mounting this in app/config.yaml inside the container (starting the deployment manually, without helm).

```
log:
  level: debug
name: "Kubernetes Authentication"
listen: "https://0.0.0.0:32443"
oidc:
  client:
    id: "loginapp"
    secret: REDACTED
    redirect_url: "https://<server>/callback"
  issuer:
    url: "https://dex.auth/dex"
    rootCA: "/etc/ssl/ca.pem"
  scopes:
    - email
    - groups
  web:
    kubeconfig:
      extraOpts: {}
tls:
  enabled: false
clusters:
  - name: mycluster
    server: https://mycluster:7443
    certificate-authority: |
        -----BEGIN CERTIFICATE-----
       ...
        -----END CERTIFICATE-----
    insecure-skip-tls-verify: false
web:
  mainClientID: "loginapp"
  mainUsernameClaim: "email"
  kubeconfig:
    extraOpts: {}
```

deployment:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex-loginapp
  namespace: auth
  labels:
    app: dex-loginapp
spec:
  replicas: 1
  ...
    spec:
      containers:
      - name: dex-loginapp
        #image: objectiflibre/login-app:latest
        image: quay.io/fydrah/loginapp:latest
        command: ["/loginapp"]
        args: ["serve", "/app/config.yaml"]
        volumeMounts:
        - mountPath: /etc/ssl/ca.pem
          name: dex-ca
          readOnly: true
        - mountPath: /app/config.yaml
          name: loginapp-config
          readOnly: true
      volumes:
      - hostPath:
          path: /cephfs/certs/dex/ssl/ca.pem
          type: File
        name: dex-ca
      - hostPath:
          path: /cephfs/volumes/dex-loginapp/config.yaml
          type: File
        name: loginapp-config
```

**Comment by sense-amid-madness** [comment]
Now I managed to get past the error using the older version 2.5.0, but first was stuck at "no root_ca specified".

With some experimenting, I found that it works with "root_ca" instead of "rootCA" as in the example config from the front page.

Moving back to v3.2.0, I noticed that also here, I can work around the above error by specifying "extra_opts" instead of "extraOpts".

I guess it's my fault and there is something fundamental I do not understand yet - do you have to adapt the names in some way when moving from your config format to the one I use in the example above? I know a bug forum is not the right place to ask, but could you maybe give a hint or a link to documentation which explains why?

Thanks much. Anyway, I have a working configuration now, will report back if anything else creeps up.

**Comment by fydrah** [comment]
Hi @sense-amid-madness ,

This is a known issue reported in #37 .

I just push a fix in v3.2.1 (helm chart v1.0.5).

btw, the change from `root_ca` to `rootCA` has been made in v3.0.0 (check [release note](https://github.com/fydrah/loginapp/releases/tag/v3.0.0) ), all yml keys are now in lower camel case format. This was required for the change to cobra/viper CLI libs, and to allow overrrides from configuration file, environment vars & CLI args.

**Comment by sense-amid-madness** [comment]
Thanks for your help, this explains much of the confusion with the names I had. I thought the fix for the previous issue was already online, so I was wondering why I was still getting it. I am only still confused why I could not work around it by defining the extraOpts manually, but maybe I made a mistake there.

I'll wait for v3.2.1 to show up on quay.io/fydrah and hope this will make everything work.

**Comment by fydrah** [comment]
```
listen: "0.0.0.0:32443" # without scheme
# Application secret. Must be identical across
# all loginapp server replicas ( /!\ this is not the OIDC Client secret)
secret: REDACTED # not present
oidc:
  client:
    redirectURL: "https://<server>/callback" # lower camel case
```
You should compare with https://github.com/fydrah/loginapp#configuration

Yes quay.io take is slow today. You can use master tag if you want to try, it is currently the same as v3.2.1.
