### ISSUE TITLE
Missing refresh token

### ISSUE THREAD

**Issue by knfoo** [fydrah/loginapp#41]
**Describe the bug**
I have setup loginapp with helm with `refreshToken: "true"`
But I do not get a refresh token

**Loginapp & Dex version**
loginapp: `latest`
dex: `v2.26.0`

**Configuration**
I have not done a lot of configuration changes from the values.yaml file.

```
config:
  name: auth-login
  secret: "..."
  clientID: "login-cnp"
  clientSecret: "..."
  clientRedirectURL:
  issuerRootCA: # +doc-gen:break
    configMap:
    key: ca.pem
  issuerInsecureSkipVerify: true
  issuerURL: "https://dex/dex"
  refreshToken: "true"
  tls:
    enabled: false
    secretName:
    altnames: []
    altIPs: []
  # List of kubernetes clusters to add on web frontend
  clusters:
    - name: dc9-1
      server: https://k8s-api:6443
      certificate-authority: |
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
        #insecure-skip-tls-verify: false
```
Install Dex and connect it to AD with the ldap integration.

**Expected behavior**
I would expect to get a refresh token so that I do not need to login everyday.

If I run loginapp in debug I can tell that the scopes reflect that I would want offline access.
`{"level":"debug","msg":"request token with the following scopes: [openid profile email groups offline_access]`

And
```
Extra:{Scopes:[] AuthCodeOpts:map[]} OfflineAsScope:true CrossClients:[] Scopes:[openid profile email groups]}
``` 

I am not sure if I am missing something. 
I have read https://github.com/fydrah/loginapp/issues/11 but it seems that the config has changed somewhat since 2018.
