### ISSUE TITLE
Issues with LetsEncrypt certificates

### ISSUE THREAD

**Issue by Demonsthere** [fydrah/loginapp#5]
Hi,
I have been using Your loginapp as a part of the [k8s-ldap](https://github.com/ObjectifLibre/k8s-ldap) setup, however I have encountered a problem with handling certificates that were created by [cert-manager](https://cert-manager.readthedocs.io/en/latest/):

`x509: certificate signed by unknown authority`

I suspect that the problem is, that the loginapp is based on scratch and doest not have the LetsEncrypt or any other ca.

Best regards

**Comment by fydrah** [comment]
Hi @Demonsthere ,

Yes, you must mount letsencrypt CA on the loginapp pod, and use the following configuration for loginapp:
```
    name: "Kubernetes Auth"
    listen: "0.0.0.0:8080"
    oidc:
      client:
        id: "cli"
        secret: XXXXXXXXXXXXXXX
        redirect_url: "https://xxxxxxxxxxxxx/callback"
      issuer:
        root_ca: "/etc/ssl/ca.pem" # <<<<< here is letsencrypt root CA from your configmap
        url: "https://xxxxxxxxxxxx"
      extra_scopes:
        - groups
      offline_as_scope: true
      cross_clients:
      - kubernetes
    tls:
      enabled: false
    log:
      level: debug
      format: json
    web_output:
      main_client_id: kubernetes
```
