### ISSUE TITLE
Issues with dex new release 2.30.0

### ISSUE THREAD

**Issue by HenryXie1** [fydrah/loginapp#50]
**Describe the bug**
After deploy new release of dex 2.30.0 via 
https://github.com/dexidp/dex/blob/master/examples/k8s/dex.yaml

The loginapp is not working as expected

**Loginapp & Dex version**
loginapp: `v3.2.3`
dex: `v2.30.0`

**Configuration**

Current loginapp (and eventually dex) configuration (*without secrets*)
```
oidc:
      client:
        id: "testloginapp"
        # This isn't a real secret as it's given to all users for the refresh token
        secret: ****
        redirectURL: "https://www.dexexample.com:32000/callback"
      issuer:
        rootCA: "/etc/loginapp/cfg/CA.pem"
        url: "https://www.dexexample.com:32000/dexidp"
        insecureSkipVerify: false
      # List of scopes to request.
      # Updating this parameter will override existing scopes.
      # Default:[openid,profile,email,groups]
      scopes: []
      offlineAsScope: false
      crossClients: []
    tls:
      enabled: false
    log:
      level: debug
      format: json
    web:
      # ClientID to output (useful for cross_client)
      # default: value of 'oidc.client.id'
      mainClientID: testloginapp
      # Claims to use for kubeconfig username.
      # default: email
      mainUsernameClaim: email
      # Kubeconfig output format
      kubeconfig:
        # Change default cluster for kubeconfig context
        # Default: first cluster name in `clusters`
        defaultCluster: test1
        # Change default namespace for kubeconfig contexts
        # Default: default
        defaultNamespace: default
        # Change default context for kubeconfig
        # If not set, use a format like 'defaultClusterName'/'usernameClaim'
        # Default: ""
        defaultContext: test
        # Extra key/value pairs to add to kubeconfig output.
        # Key/value pairs are added under `user.auth-provider.config`
        # dictionnary into the kubeconfig.
        # Ex:
        # extraOpts:
        #   mykey1: value1
        #
        # Kubeconfig Output:
        # - name: user.name@example.org
        #     auth-provider:
        #       config:
        #         mykey1: value1
        #         client-id: loginapp
        #         [...]
        extraOpts: {}
    # Metrics configuration
    metrics:
      # Port to use. Metrics are available at
      # http://IP:PORT/metrics
      # default: 9090
      port: 9090

    # Clusters list for CLI configuration
    clusters:
      - name: test1
        server: https://****:6443
        certificate-authority: |
          -----BEGIN CERTIFICATE-----
          MIIC5zCCAc+gAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
          ******
          -----END CERTIFICATE-----
        insecure-skip-tls-verify: false
        # Alternative context name for this cluster
        contextName: test
```

**To Reproduce**
1. Go to loginapp 
2. See error 
```
invalid_scope: Missing required scope(s) ["openid"].
internal server error
```
url is https://www.dexexample.com:32000/callback?error=invalid_scope&error_description=Missing+required+scope%28s%29+%5B%22openid%22%5D.&state=5P1QJkKHQi9rk42uHLJUUPQBy%2B7jxnAbJuk12znxqPY%3D

**Expected behavior**
expect github login page

**Screenshots**

**Additional context**
1. we use nginx as reverse proxy in the pod,  the pod has 3 containers dex, loginapp, nginx
```
   upstream dex {
      server 127.0.0.1:5556;
    }
    upstream loginapp {
      server 127.0.0.1:5555;
    }
    server {
      listen              32000 ssl default_server;
      ssl_certificate     /etc/nginx/ssl/tls.crt;
      ssl_certificate_key /etc/nginx/ssl/tls.key;
      location /dexidp {
        proxy_pass http://dex;
      }
      location / {
        proxy_pass http://loginapp;
      }
    }
```
2. dex config file is 
```
issuer: https://www.dexexample.com:32000/dexidp
    storage:
      type: kubernetes
      config:
        inCluster: true
    frontend:
      theme: tectonic
    web:
      http: 127.0.0.1:5556
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://www.dexexample.com:32000/dexidp/callback
        hostName: www.github.com
    oauth2:
      skipApprovalScreen: false

    staticClients:
    - id: testloginapp
      redirectURIs:
      - 'http://127.0.0.1:5555/callback'
      - 'https://www.dexexample.com:32000/callback'
      name: 'testoginapp'
      secret: ****
```
3. I test dex 2.30.0 via example-app in below doc, it is working fine though, 
https://dexidp.io/docs/connectors/github/#run-example-client-app-with-github-config
I also notice dex 2.30.0 was released later than loginapp 3.2.3
