### ISSUE TITLE
failed to query provider and 404 error 

### ISSUE THREAD

**Issue by HenryXie1** [fydrah/loginapp#51]
**Describe the bug**
After deploy new release of dex 2.30.0 via 
https://github.com/dexidp/dex/blob/master/examples/k8s/dex.yaml

The loginapp is not working as expected

**Loginapp & Dex version**
loginapp: `v3.2.3`
dex: `v2.30.0`

**Configuration**

Current loginapp (and eventually dex) configuration (*without secrets*)
```
oidc:
      client:
        id: "testloginapp"
        # This isn't a real secret as it's given to all users for the refresh token
        secret: ****
        redirectURL: "https://www.dexexample.com:32000/callback"
      issuer:
        rootCA: "/etc/loginapp/cfg/CA.pem"
        url: "https://www.dexexample.com:32000/dexidp"
        insecureSkipVerify: false
      # List of scopes to request.
      # Updating this parameter will override existing scopes.
      # Default:[openid,profile,email,groups]
      scopes: [openid,profile,email,groups]
      offlineAsScope: false
      crossClients: []
    tls:
      enabled: false
    log:
      level: debug
      format: json
    web:
      # ClientID to output (useful for cross_client)
      # default: value of 'oidc.client.id'
      mainClientID: testloginapp
      # Claims to use for kubeconfig username.
      # default: email
      mainUsernameClaim: email
      # Kubeconfig output format
      kubeconfig:
        # Change default cluster for kubeconfig context
        # Default: first cluster name in `clusters`
        defaultCluster: test1
        # Change default namespace for kubeconfig contexts
        # Default: default
        defaultNamespace: default
        # Change default context for kubeconfig
        # If not set, use a format like 'defaultClusterName'/'usernameClaim'
        # Default: ""
        defaultContext: test
        # Extra key/value pairs to add to kubeconfig output.
        # Key/value pairs are added under `user.auth-provider.config`
        # dictionnary into the kubeconfig.
        # Ex:
        # extraOpts:
        #   mykey1: value1
        #
        # Kubeconfig Output:
        # - name: user.name@example.org
        #     auth-provider:
        #       config:
        #         mykey1: value1
        #         client-id: loginapp
        #         [...]
        extraOpts: {}
    # Metrics configuration
    metrics:
      # Port to use. Metrics are available at
      # http://IP:PORT/metrics
      # default: 9090
      port: 9090

    # Clusters list for CLI configuration
    clusters:
      - name: test1
        server: https://****:6443
        certificate-authority: |
          -----BEGIN CERTIFICATE-----
          MIIC5zCCAc+gAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
          ******
          -----END CERTIFICATE-----
        insecure-skip-tls-verify: false
        # Alternative context name for this cluster
        contextName: test
```

**To Reproduce**
1. Go to loginapp 
2.  login github
3.  got kubeconfig successfully
4. tail logs of loginapp 
```
$ k logs -f dex-6475b86b87-tz2t7 -c loginapp
{"level":"info","msg":"no secret defined, using a random secret but it is strongly advised to add a secret since without it requests cannot be load balanced between multiple server","time":"2021-10-10T22:53:24Z"}
{"level":"error","msg":"failed to query provider \"https://www.dexexample.com:32000/dexidp\": 502 Bad Gateway: \u003chtml\u003e\r\n\u003chead\u003e\u003ctitle\u003e502 Bad Gateway\u003c/title\u003e\u003c/head\u003e\r\n\u003cbody\u003e\r\n\u003ccenter\u003e\u003ch1\u003e502 Bad Gateway\u003c/h1\u003e\u003c/center\u003e\r\n\u003chr\u003e\u003ccenter\u003enginx/1.17.8\u003c/center\u003e\r\n\u003c/body\u003e\r\n\u003c/html\u003e\r\n","time":"2021-10-10T22:53:24Z"}
{"level":"info","msg":"export metric on http://0.0.0.0:9090","time":"2021-10-10T22:53:24Z"}
{"level":"info","msg":"listening on http://127.0.0.1:5555","time":"2021-10-10T22:53:24Z"}
{"code":404,"level":"info","method":"GET","msg":"","path":"/.well-known/openid-configuration","protocol":"HTTP/1.0","remote_address":"127.0.0.1:58920","request_duration":"22.5µs","time":"2021-10-10T22:53:34Z"}
{"code":404,"level":"info","method":"GET","msg":"","path":"/.well-known/openid-configuration","protocol":"HTTP/1.0","remote_address":"127.0.0.1:59006","request_duration":"33.2µs","time":"2021-10-10T22:53:44Z"}
```

**Expected behavior**
1. I have secret set in loginapp config, not sure why still has log "no secret defined....."
2. expect no "failed to query provider" and 404 error in loginapp logs

**Screenshots**

**Additional context**
1. We run a [kind](https://kind.sigs.k8s.io/docs/user/quick-start/) cluster for it. We spoof 127.0.0.1 for www.dexexample.com on the machine. We use nginx as reverse proxy in the pod,  the pod has 3 containers dex, loginapp, nginx and use nodeport 32000 to expose service.  It is working fine to get kubeconfig file,but quite a few error in loginapp logs. 
```
   upstream dex {
      server 127.0.0.1:5556;
    }
    upstream loginapp {
      server 127.0.0.1:5555;
    }
    server {
      listen              32000 ssl default_server;
      ssl_certificate     /etc/nginx/ssl/tls.crt;
      ssl_certificate_key /etc/nginx/ssl/tls.key;
      location /dexidp {
        proxy_pass http://dex;
      }
      location / {
        proxy_pass http://loginapp;
      }
    }
```
2. dex config file is 
```
issuer: https://www.dexexample.com:32000/dexidp
    storage:
      type: kubernetes
      config:
        inCluster: true
    frontend:
      theme: tectonic
    web:
      http: 127.0.0.1:5556
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://www.dexexample.com:32000/dexidp/callback
        hostName: www.github.com
    oauth2:
      skipApprovalScreen: false

    staticClients:
    - id: testloginapp
      redirectURIs:
      - 'http://127.0.0.1:5555/callback'
      - 'https://www.dexexample.com:32000/callback'
      name: 'testoginapp'
      secret: ****
```
