### ISSUE TITLE
kubectl 1.22 reports context was not found for specified context 

### ISSUE THREAD

**Issue by jkroepke** [fydrah/loginapp#52]
**Describe the bug**
kubectl is not going to work with the full kubeconfig provided by loginapp

```
% kubectl create ns playground
Error in configuration: context was not found for specified context: dev/github@jkroepke.de
```

**Loginapp & Dex version**
loginapp: `v3.2.3`

**To Reproduce**
1. login into loginapp
2. Click on 'full kubeconfig'
3. copy then to local filesystem to $HOME/.kube/config
4. run any command with kubectl (v1.22+)

**Expected behavior**
kubectl just works

**Additional context**

this is the head of the kubeconfig file:

```
apiVersion: v1
kind: Config
preferences: {}
current-context: dev/github@jkroepke.de
contexts:
- name: dev
  context:
    user: github@jkroepke.de
    cluster: dev
    namespace: default
clusters:
- name: dev
```

If I modifiy `current-context` to just `dev`, like `current-context: dev`, then everything works as expected.

**Comment by fydrah** [comment]
Hi,

I tested the generated kubeconfig with kubectl v1.22.3, it works as expected with no error:
```
$ KUBECONFIG=/tmp/examplecluster.yaml kubectl config view --minify
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://REDACTED
  name: examplecluster
contexts:
- context:
    cluster: examplecluster
    namespace: default
    user: admin@example.com
  name: examplecluster/admin@example.com
current-context: examplecluster/admin@example.com
kind: Config
preferences: {}
users:
- name: admin@example.com
  user:
    auth-provider:
      config:
        client-id: loginapp-local
        id-token: DATA+OMITTED
        idp-issuer-url: https://dex.172.17.0.2.nip.io:32000
      name: oidc
```

What is your error message exactly?

**Comment by jkroepke** [comment]
i agree. it was my fault. i figure out, bot setting need to be unset or set to equal values.

````yaml


web:
  kubeconfig:
    defaultContext: altcontextname
    
clusters:
  - contextName: altcontextname
```
