### ISSUE TITLE
Use base64 for cluster certificate authority

### ISSUE THREAD

**Issue by HenryXie1** [fydrah/loginapp#53]
We are automating deploy loginapp + dex.  We have difficulty on replace cluster certificate-authority strings.
```
          -----BEGIN CERTIFICATE-----
          MIIC5zCCAc+gAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
          ******
          -----END CERTIFICATE-----
```
It has pem format which has many lines and /n. The automation has difficulty to replace certficate-authority strings for different clusters. 
Do you support base64 encode string for this certificate-authority? like

```
    # Clusters list for CLI configuration
    clusters:
      - name: test1
        server: https://****:6443
        certificate-authority: |
          <base64 encoded string>
        insecure-skip-tls-verify: false
        # Alternative context name for this cluster
        contextName: test
```
or any workaround would be much appreciated.

Thank you
Henry
