### ISSUE TITLE
404 error after we have nginx proxy in front of loginapp

### ISSUE THREAD

**Issue by HenryXie1** [fydrah/loginapp#54]
**Describe the bug**
After we put loginapp behind our nginx proxy, 
it was working well when we have domain without /auth.   ie https://www.dexexample.com/
then we config nginx proxy to route traffic. domain/auth --> loginapp container  domain/dex --> dex container 
ie https://www.dexexample.com/auth
we got below error from loginapp logs

{"code":404,"level":"info","method":"GET","msg":"","path":"/auth","protocol":"HTTP/1.0","remote_address":"10.40.162.170:44986","request_duration":"28.515µs","time":"2021-12-06T00:38:03Z"}
{"code":404,"level":"info","method":"GET","msg":"","path":"/auth","protocol":"HTTP/1.0","remote_address":"10.40.162.170:45086","request_duration":"28.755µs","time":"2021-12-06T00:38:13Z"}
{"code":404,"level":"info","method":"GET","msg":"","path":"/auth/callback","protocol":"HTTP/1.0","remote_address":"10.40.162.170:37252","request_duration":"113.203µs","time":"2021-12-06T01:10:41Z"}

**Loginapp & Dex version**
loginapp: `v3.2.3`
dex: `v2.30.0`

**Configuration**

Current loginapp configuration (*without secrets*)
```
oidc:
      client:
        id: "testloginapp"
        # This isn't a real secret as it's given to all users for the refresh token
        secret: ****
        redirectURL: "https://www.dexexample.com/auth/callback"
      issuer:
        rootCA: "/etc/loginapp/cfg/CA.pem"
        url: "https://www.dexexample.com/dex"
        insecureSkipVerify: false
      # List of scopes to request.
      # Updating this parameter will override existing scopes.
      # Default:[openid,profile,email,groups]
      scopes: [openid,profile,email,groups]
      offlineAsScope: false
      crossClients: []
    tls:
      enabled: false
    log:
      level: debug
      format: json
    web:
      # ClientID to output (useful for cross_client)
      # default: value of 'oidc.client.id'
      mainClientID: testloginapp
      # Claims to use for kubeconfig username.
      # default: email
      mainUsernameClaim: email
      # Kubeconfig output format
      kubeconfig:
        # Change default cluster for kubeconfig context
        # Default: first cluster name in `clusters`
        defaultCluster: test1
        # Change default namespace for kubeconfig contexts
        # Default: default
        defaultNamespace: default
        # Change default context for kubeconfig
        # If not set, use a format like 'defaultClusterName'/'usernameClaim'
        # Default: ""
        defaultContext: test
        # Extra key/value pairs to add to kubeconfig output.
        # Key/value pairs are added under `user.auth-provider.config`
        # dictionnary into the kubeconfig.
        # Ex:
        # extraOpts:
        #   mykey1: value1
        #
        # Kubeconfig Output:
        # - name: user.name@example.org
        #     auth-provider:
        #       config:
        #         mykey1: value1
        #         client-id: loginapp
        #         [...]
        extraOpts: {}
    # Metrics configuration
    metrics:
      # Port to use. Metrics are available at
      # http://IP:PORT/metrics
      # default: 9090
      port: 9090

    # Clusters list for CLI configuration
    clusters:
      - name: test1
        server: https://****:6443
        certificate-authority: |
          -----BEGIN CERTIFICATE-----
          MIIC5zCCAc+gAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
          ******
          -----END CERTIFICATE-----
        insecure-skip-tls-verify: false
        # Alternative context name for this cluster
        contextName: test
```

**To Reproduce**
1. Go to <domain>/auth 
2.  lt reports 404 error

**Expected behavior**

I expect loginapp redirects page to github login page

**Screenshots**

**Additional context**
1.  We use nginx as reverse proxy in the separate deployment
```
   nginx-proxy.conf: |
    upstream dex {
      server auth-dex-login.oidc-auth.svc.dexexample.com:5556;
    }
    upstream loginapp {
      server auth-dex-login.oidc-auth.svc.dexexample.com:5555;
    }
    server {
      listen              443 ssl;
      server_name         www.dexexample.com;
      ssl_certificate     /etc/nginx/ssl/tls.crt;
      ssl_certificate_key /etc/nginx/ssl/tls.key;
      location /dex {
        proxy_pass http://dex;
      }
      location / {
        root /usr/local/nginx/html;
        index index.htm index.html;
      
      }
      location /auth {
        proxy_pass http://loginapp;
      }
      
    }
```
2. dex config file is 
```
issuer: https://www.dexexample.com/dex
    storage:
      type: kubernetes
      config:
        inCluster: true
    frontend:
      theme: tectonic
    web:
      http: 0.0.0.0:5556
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $GITHUB_CLIENT_ID
        clientSecret: $GITHUB_CLIENT_SECRET
        redirectURI: https://www.dexexample.com/dex/callback
        hostName: www.github.com
    oauth2:
      skipApprovalScreen: false

    staticClients:
    - id: testloginapp
      redirectURIs:
      - 'http://127.0.0.1:5555/callback'
      - 'https://www.dexexample.com/auth/callback'
      name: 'testoginapp'
      secret: ****
```
