### ISSUE TITLE
loginapp cannot start

### ISSUE THREAD

**Issue by thiDucTran** [fydrah/loginapp#59]
```yaml
log:
  level: debug
replicas: 1
image: quay.io/fydrah/loginapp:v3.2.3
imagePullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 5555

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env: {}

args: []

config:
  # Application name, defaults to Release name
  name:
  # Application secret
  # Use an existing secret for the loginapp secret and OIDC secret
  existingSecret:
  # if empty, generate a random string
  # please setup a real secret otherwise helm will generate
  # a new secret at each deployment
  secret: "test123"
  # OIDC Client ID
  clientID: "loginapp"
  # OIDC Client secret
  clientSecret: "clientSecretHere"
  # OIDC Client redirect URL
  # This must end with /callback
  # if empty, defaults to:
  #
  # 1. '{{ .Values.ingress.hosts[0].host }}/callback' if 'ingress.enabled: true' and 'ingress.hosts[0]' exists
  # 2. '{{ .Release.Name }}.{{ .Release.Namespace }}.svc:5555/callback'
  clientRedirectURL: https://loginappURL/callback
  # Issuer root CA configMap
  # ConfigMap containing the root CA
  # and key to use inside the configMap.
  # This configMap must exist
  issuerRootCA: # +doc-gen:break
    configMap: godaddy-ca
    key: ca.crt
  # Skip issuer certificate validation
  # This is usefull for testing purpose, but
  # not recommended in production
  issuerInsecureSkipVerify: false
  # Issuer url
  issuerURL: "https://dexUrl:5556"
  # Include refresh token in request
  refreshToken: false
  tls:
    # Enable TLS for deployment
    enabled: false
  clusters:
   - name: appcluster
     server: https://apiserver.app-cluster.capz.io:6443
     certificate-authority: |
       -----BEGIN CERTIFICATE-----
       MIIC6jCCAdKgAwIBAgIBADANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwprdWJl
       -----END CERTIFICATE-----
     insecure-skip-tls-verify: false
     # Alternative context name for this cluster
     contextName: app-cluster

# Configuration overrides, this is a free configuration merged
# with the previous generated configuration 'config'. Use this
# to add or overwrites values.
# Example:
#
#  oidc:
#    scopes: [openid,profile,email]
configOverwrites: {}


# Configuration overrides html templates content used by loginapp to display error and token pages
# Example:
#
#  templates:
#    token.html: |-
#      {{`<html>
#      <body>
#      <title>Hello token</title>
#      </body>
#      </html>`}}
templates: {}

# Enable dex deployment
# See https://github.com/dexidp/helm-charts/tree/master/charts/dex
# more information about available values
dex:
  enabled: false
```

then I do `helm install loginapp loginapp/loginapp -n default --values values.yaml` ...Pod is in restart loop ...tried to enable debug log but there is not debug log when pod crashes...pod health checks are failing..as expected..but cannot figure out why loginapp pod cannot start.

![image](https://user-images.githubusercontent.com/37130368/209166146-604a5947-e935-43fa-a00f-d427e48d1163.png)
![image](https://user-images.githubusercontent.com/37130368/209166287-034c4191-a146-44b7-93c1-3b291312a939.png)

it's a bit confusing because I got everything working..then deleted and started over just as practice and to confirm everything...and ran into this ;)

I tried to deploy with only required configs in `values.yaml` ..but still crash loop ...what else could be the cause of loginapp not being able to start?
