### ISSUE TITLE
Pod restart with warning

### ISSUE THREAD

**Issue by lbouquinD** [fydrah/loginapp#65]
**Describe the bug**
I use helm  chart loginapp-v1.3.1 and I have some issue about it: 
-> mode debug doesn't working: 
`configOverwrites: 
  log:
    level: Debug
    format: json` but no debug message appear 

-> Pods restart for no reason: 
In log pod I have this: 
```
[root@kubernetes loginapp]# kubectl logs loginapp-84fbfc4fdc-krs2x
{"level":"info","msg":"No cluster defined, setting default cluster output to none","time":"2023-05-05T06:55:51Z"}
{"level":"**error**","msg":"Certificate validation is currently disabled, this is not a recommended behavior for production","time":"2023-05-05T06:55:51Z"}
```

**Loginapp & Dex version**
loginapp: `v3.2.3`
dex: `v2.36.0`

**Configuration**

Current loginapp (and eventually dex) configuration (*without secrets*)
```
config:
  web:
    mainClientID: kubernetes
  name: my-login-app
  existingSecret:
  secret:
  clientID: "loginapp"
  clientSecret: "test"
  clientRedirectURL:
  issuerRootCA: # +doc-gen:break
    configMap:
    key: ca.crt
  issuerInsecureSkipVerify: true
  issuerURL: "http://dextest.default.svc.cluster.local:5556/dex"
  refreshToken: false
  tls:
    enabled: false
    secretName:
    altnames: []
    altIPs: []
  # List of kubernetes clusters to add on web frontend
  clusters: []

configOverwrites: 
  log:
    level: Debug
    format: json
  oidc:
    issuer:
      insecureSkipVerify: true
    crossClients:
      - kubernetes
  web:
    mainClientID: kubernetes
```

**To Reproduce**
1. helm  install loginapp
2. check logs login app  

**Expected behavior**
Pod have to start  and running state  

**Additional context**
