### ISSUE TITLE
No required SSL certificate was sent

### ISSUE THREAD

**Issue by arminioa** [fydrah/loginapp#9]
Hi,

I'm trying to deploy dex and loginapp in a kubernetes cluster.
Both dex and loginapp are exposed through a nginx ingress controller and both require authentication with client certificates.
With this setup, loginapp is not able to connect to dex since dex needs a client certificate and its private key in order to accept the connection.
I suppose that loginapp configuration for issuer(dex in my case) should be extended with 2 optional  keys `client_cert` and `client_key` as bellow:
```
issuer:
  root_ca: "/etc/ssl/ca.pem"
  client_cert: "/etc/ssl/client-cert.pem"
  client_key: "/etc/ssl/client-key.pem"
  url: "https://dex.mydomain.com"
```
 This is my error :
```
{"level":"error","msg":"Failed to query provider \"https://dex.mydomain.com\": 400 Bad Request: \u003chtml\u003e\r\n\u003chead\u003e\u003ctitle\u003e400 No required SSL certificate was sent\u003c/title\u003e\u003c/head\u003e\r\n\u003cbody bgcolor=\"white\"\u003e\r\n\u003ccenter\u003e\u003ch1\u003e400 Bad Request\u003c/h1\u003e\u003c/center\u003e\r\n\u003ccenter\u003eNo required SSL certificate was sent\u003c/center\u003e\r\n\u003chr\u003e\u003ccenter\u003enginx\u003c/center\u003e\r\n\u003c/body\u003e\r\n\u003c/html\u003e\r\n","time":"2018-10-25T09:55:23Z"}
``` 
Thanks
